cudami:
  server:
    url: http://localhost:9000
    #url: https://api-dev.digitale-sammlungen.de/cudami

management:
  endpoints:
    web:
      base-path: "/monitoring"
      exposure:
        include: "*"
  server:
    port: 18080

server:
  port: 8080
  server-header: "@project.name@ v@project.version@"

spring:
  main:
    banner-mode: 'off'
  profiles:
    active: local
  security:
    user:
      name: admin
      password: secret
      roles: MONITORING