cudami:
  server:
    url: http://localhost:9000

management:
  endpoints:
    web:
      base-path: "/monitoring"
      exposure:
        include:
          - prometheus
          - metrics
          - info
          - health
  server:
    port: 18081

server:
  port: 8081
  server-header: "@project.name@ v@project.version@"

spring:
  devtools:
    add-properties: false
  main:
    banner-mode: 'off'
  profiles:
    active: local
  security:
    user:
      name: admin
      password: secret
      roles: MONITORING